import type { MenuData } from "@/types/menu"

export const MOCK_MENU: MenuData = {
  id: "mock-izakaya-01",
  sourceImageName: "izakaya-menu.jpg",
  currency: "JPY",
  createdAt: new Date().toISOString(),
  categories: [
    {
      id: "starters",
      name: "Starters",
      items: [
        {
          id: "edamame",
          originalName: "枝豆",
          englishName: "Steamed Edamame",
          price: 380,
          description: "Salted young soybeans, lightly seasoned",
          categoryId: "starters",
        },
        {
          id: "agedashi-tofu",
          originalName: "揚げ出し豆腐",
          englishName: "Agedashi Tofu",
          price: 550,
          description: "Deep-fried silken tofu in dashi broth with grated daikon",
          categoryId: "starters",
        },
        {
          id: "gyoza",
          originalName: "餃子",
          englishName: "Pan-Fried Gyoza",
          price: 680,
          description: "Crispy pork dumplings with soy-vinegar dipping sauce (6 pcs)",
          categoryId: "starters",
        },
        {
          id: "karaage",
          originalName: "唐揚げ",
          englishName: "Chicken Karaage",
          price: 750,
          description: "Juicy fried chicken thigh with lemon and Japanese mayo",
          categoryId: "starters",
        },
      ],
    },
    {
      id: "mains",
      name: "Mains",
      items: [
        {
          id: "miso-ramen",
          originalName: "味噌ラーメン",
          englishName: "Miso Ramen",
          price: 1280,
          description: "Rich pork miso broth, chashu pork, spring onion, soft egg",
          categoryId: "mains",
        },
        {
          id: "tonkotsu-ramen",
          originalName: "豚骨ラーメン",
          englishName: "Tonkotsu Ramen",
          price: 1380,
          description: "Creamy pork bone broth, bamboo shoots, nori, menma",
          categoryId: "mains",
        },
        {
          id: "katsu-curry",
          originalName: "カツカレー",
          englishName: "Pork Katsu Curry",
          price: 1480,
          description: "Panko-breaded pork cutlet on Japanese curry with steamed rice",
          categoryId: "mains",
        },
        {
          id: "yakisoba",
          originalName: "焼きそば",
          englishName: "Yakisoba Noodles",
          price: 980,
          description: "Stir-fried wheat noodles with pork, cabbage and pickled ginger",
          categoryId: "mains",
        },
      ],
    },
    {
      id: "skewers",
      name: "Skewers",
      items: [
        {
          id: "chicken-thigh",
          originalName: "もも焼き鳥",
          englishName: "Chicken Thigh Yakitori",
          price: 320,
          description: "Grilled chicken thigh with sweet tare glaze (2 skewers)",
          categoryId: "skewers",
        },
        {
          id: "tsukune",
          originalName: "つくね",
          englishName: "Chicken Meatball Skewer",
          price: 350,
          description: "Minced chicken ball, sweet soy glaze, runny egg dip",
          categoryId: "skewers",
        },
        {
          id: "pork-belly",
          originalName: "豚バラ焼き鳥",
          englishName: "Pork Belly Yakitori",
          price: 330,
          description: "Grilled pork belly strips with spring onion (2 skewers)",
          categoryId: "skewers",
        },
        {
          id: "asparagus-bacon",
          originalName: "アスパラベーコン",
          englishName: "Asparagus & Bacon Roll",
          price: 340,
          description: "Crispy bacon wrapped around fresh asparagus spears",
          categoryId: "skewers",
        },
      ],
    },
    {
      id: "drinks",
      name: "Drinks",
      items: [
        {
          id: "draft-beer",
          originalName: "生ビール",
          englishName: "Draft Beer",
          price: 580,
          description: "Sapporo Premium, medium glass",
          categoryId: "drinks",
        },
        {
          id: "yuzu-sour",
          originalName: "ゆずサワー",
          englishName: "Yuzu Sour Cocktail",
          price: 520,
          description: "Yuzu citrus, shochu base, sparkling soda",
          categoryId: "drinks",
        },
        {
          id: "hot-sake",
          originalName: "熱燗",
          englishName: "Hot Sake",
          price: 480,
          description: "House sake served warm in a ceramic tokkuri",
          categoryId: "drinks",
        },
        {
          id: "green-tea",
          originalName: "緑茶",
          englishName: "Japanese Green Tea",
          price: 250,
          description: "Hot or iced, free refills",
          categoryId: "drinks",
        },
      ],
    },
  ],
}
